name: social_share
description: Wide variety of sharing options you'll need to share directly to certain well-known apps.
version: 2.0.0
author: Shekar Mudaliyar <sskshekar10@gmail.com>
homepage: https://github.com/ShekarMudaliyar/social_share

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.shekarmudaliyar.social_share
    pluginClass: SocialSharePlugin
