name: social_share
description: Wide variety of sharing options you'll need to share directly to certain well-known apps.
version: 2.3.1
homepage: https://github.com/ShekarMudaliyar/social_share

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.shekarmudaliyar.social_share
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin